services:
  db:
    image: 'postgres:15.2'
    restart: always
    container_name: taskmanager_postgresql
    environment:
      POSTGRES_DB: taskmanager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: taskmanager_spring
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    restart: unless-stopped

volumes:
  db_data: